apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-strapi-sync-wizard
  labels:
    helm.sh/chart: strapi-sync-wizard-0.2.1
    app.kubernetes.io/name: strapi-sync-wizard
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.6"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: strapi-sync-wizard
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: strapi-sync-wizard
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-strapi-sync-wizard
      securityContext:
        {}
      containers:
        - name: strapi-sync-wizard
          securityContext:
            {}
          image: "isebben/strapi-sync-wizard:0.0.3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
            - name: DEVELOPMENT_MODE
              value: "false"
            - name: JDBC_DATABASE_URL
              value: "jdbc:postgresql://release-name-strapi-sync-wizard-postgresql:5432/strapisync"
            - name: JDBC_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: release-name-strapi-sync-wizard
                  key: database-username
            - name: JDBC_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-strapi-sync-wizard
                  key: database-password
            - name: JDBC_MAXIMUM_POOL_SIZE
              value: "3"
            - name: DB_SALT
              valueFrom:
                secretKeyRef:
                  name: release-name-strapi-sync-wizard
                  key: database-salt
            - name: DATA_FOLDER
              value: /app/data
            - name: STRAPI_CLIENT_TIMEOUT
              value: "30000"
            - name: STRAPI_CLIENT_MAX_RETRIES
              value: "3"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {}
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: release-name-strapi-sync-wizard
